# 多环境配置文件激活属性
server:
  port: 8778
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      validation-query: SELECT 1 FROM DUAL
      initial-size: 1
      min-idle: 10
      max-active: 20
  #页面热加载
  thymeleaf:
    cache: false